import type { Metadata } from 'next'

import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { notFound } from 'next/navigation'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'fi']

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: {
    locale: 'en' | 'fi'
  }
}) {
  if (!locales.includes(locale as any)) notFound()

  return (
    <html lang={locale}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
